#!/usr/bin/env bash
# Quick Start Guide for Bunny HR System

echo "════════════════════════════════════════"
echo "  🚀 Bunny HR System - Quick Start"
echo "════════════════════════════════════════"
echo ""

echo "📌 Prerequisites:"
echo "  ✓ Node.js installed"
echo "  ✓ MySQL running on localhost:3306"
echo "  ✓ Database 'hr_system' exists"
echo ""

echo "🚀 Starting Servers..."
echo ""

echo "Option 1: Start in Separate Terminals (Recommended)"
echo "────────────────────────────────────────────────────"
echo ""
echo "Terminal 1 - Backend API:"
echo "  cd c:\\Users\\nuttn\\Desktop\\bunny_hr"
echo "  node backend/server.js"
echo ""
echo "Terminal 2 - Frontend:"
echo "  cd c:\\Users\\nuttn\\Desktop\\bunny_hr\\frontend"
echo "  npx http-server -p 8000"
echo ""

echo "Option 2: Start Both (Windows)"
echo "─────────────────────────────────"
echo "  cd c:\\Users\\nuttn\\Desktop\\bunny_hr"
echo "  node backend/server.js & npx http-server frontend -p 8000"
echo ""

echo "📍 Access the System:"
echo "──────────────────────"
echo "  Frontend: http://localhost:8000"
echo "  Backend:  http://localhost:3000"
echo "  Username: admin"
echo "  Password: admin123"
echo ""

echo "✨ New Features:"
echo "─────────────────"
echo "  ✓ Shift Templates - Reusable shift configurations"
echo "  ✓ Working Shifts - Employee shift assignments"
echo "  ✓ Smart Holidays - Linked to assignments (CASCADE delete)"
echo "  ✓ Improved UI - Template dropdown in forms"
echo ""

echo "📚 Documentation:"
echo "──────────────────"
echo "  • MIGRATION_COMPLETE.md - Full implementation summary"
echo "  • FRONTEND_UPDATES.md - Frontend changes explained"
echo "  • SHIFTS_REFACTORING.md - Complete refactoring guide"
echo "  • API_CHANGES.md - API endpoint reference"
echo ""

echo "✅ Migration Status:"
echo "────────────────────"
echo "  • Database schema: ✅ Updated"
echo "  • Data migration: ✅ Complete"
echo "  • Frontend code: ✅ Updated"
echo "  • Backend API: ✅ Updated"
echo ""

echo "════════════════════════════════════════"
echo "           Ready to go! 🎉"
echo "════════════════════════════════════════"
